name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: armv7-unknown-linux-gnueabihf
          override: true

      - name: Build project
        uses: actions-rs/cargo@v1.0.1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf
